// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using whatsappWeb.Data;

#nullable disable

namespace whatsappWeb.Migrations
{
    [DbContext(typeof(whatsappWebContext))]
    partial class whatsappWebContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("whatsappWeb.Models.AllRankings", b =>
                {
                    b.Property<float>("Id")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("AllRankings");
                });

            modelBuilder.Entity("whatsappWeb.Models.Ranking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float?>("AllRankingsId")
                        .HasColumnType("real");

                    b.Property<string>("author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("score")
                        .HasColumnType("int");

                    b.Property<string>("time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AllRankingsId");

                    b.ToTable("Ranking");
                });

            modelBuilder.Entity("whatsappWeb.Models.Ranking", b =>
                {
                    b.HasOne("whatsappWeb.Models.AllRankings", null)
                        .WithMany("rankings")
                        .HasForeignKey("AllRankingsId");
                });

            modelBuilder.Entity("whatsappWeb.Models.AllRankings", b =>
                {
                    b.Navigation("rankings");
                });
#pragma warning restore 612, 618
        }
    }
}
